//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User100.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User100Entities : DbContext
    {
        public User100Entities()
            : base("name=User100Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<Polzovatel> Polzovatel { get; set; }
        public virtual DbSet<Postavchik> Postavchik { get; set; }
        public virtual DbSet<Proizvoditel> Proizvoditel { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<Zakaz> Zakaz { get; set; }
        public virtual DbSet<ZakazStatus> ZakazStatus { get; set; }
    }
}
