//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User100.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        public int Id { get; set; }
        public Nullable<int> ZakazID { get; set; }
        public Nullable<int> TovarID { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
