//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User100.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovar()
        {
            this.Korzina = new HashSet<Korzina>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public string TovarName { get; set; }
        public string EdIzmerenya { get; set; }
        public Nullable<int> Cena { get; set; }
        public Nullable<int> PostavchikID { get; set; }
        public Nullable<int> ProizvoditelID { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public string Opisanye { get; set; }
        public string Foto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
        public virtual Postavchik Postavchik { get; set; }
        public virtual Proizvoditel Proizvoditel { get; set; }
    }
}
