//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User100.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Korzina = new HashSet<Korzina>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DataZakaza { get; set; }
        public Nullable<System.DateTime> DataDostavki { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<int> ZakazStatusID { get; set; }
        public Nullable<int> PolzovatelID { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual ZakazStatus ZakazStatus { get; set; }
    }
}
